// This file is part of libigl, a simple c++ geometry processing library.
//
// Copyright (C) 2014 Daniele Panozzo <daniele.panozzo@gmail.com>
//
// This Source Code Form is subject to the terms of the Mozilla Public License
// v. 2.0. If a copy of the MPL was not distributed with this file, You can
// obtain one at http://mozilla.org/MPL/2.0/.
#ifndef IGL_OPENGL_GLFW_VIEWER_H
#define IGL_OPENGL_GLFW_VIEWER_H

#ifndef IGL_OPENGL_4
#define IGL_OPENGL_4
#endif
#include "../../igl/AABB.h"
#include "../../igl_inline.h"
#include "../MeshGL.h"
#include "igl/min_heap.h"
#include "../ViewerData.h"
#include "ViewerPlugin.h"
#include <Eigen/Core>
#include <Eigen/Geometry>

#include <vector>
#include <string>
#include <cstdint>

#define IGL_MOD_SHIFT           0x0001
#define IGL_MOD_CONTROL         0x0002
#define IGL_MOD_ALT             0x0004
#define IGL_MOD_SUPER           0x0008




using namespace std;
using namespace Eigen;
using namespace igl;
namespace igl
{
namespace opengl
{
namespace glfw
{
  // GLFW-based mesh viewer
  class Viewer : public Movable
  {
  public:
      int countFrames = 0;
      int numOfzCylinder = 5;
      double xMove = 0, yMove = 0;
      struct dataVector {
          MatrixXi OF,F;
          vector<MatrixXd> Q_of_V;
          vector<set<int>> VF;
          MatrixXd OV,V;
          VectorXi EMAP;
          MatrixXi E, EF, EI;
          igl::min_heap< std::tuple<double, int, int> > QHeap = {};
          VectorXi EQ;
          MatrixXd C;
     };
      struct shapeInfo {
          int linkNumber;
          Vector3d tipCord= Vector3d(0, 0, 0);
       
      };
      int indexShape = 0;
      int shpereIndex = 0;
      int indexLoad = 0;
      Vector3d shepreCord = Vector3d(0, 0, 0);
     bool leftDir = false, rightDir = false,upDir=false,downDir=false;
     vector<dataVector*>* shapesList = new vector<dataVector*>;
     vector<AABB<Eigen::MatrixXd, 3>> treeVector;
     vector<shapeInfo> shapeinfoVector;
     vector<Vector3d> vecTipForCalc;
    // UI Enumerations
   // enum class MouseButton {Left, Middle, Right};
   // enum class MouseMode { None, Rotation, Zoom, Pan, Translation} mouse_mode;
    virtual void Init(const std::string config);
	virtual void Animate() {}
	virtual void WhenTranslate() {}
	virtual Eigen::Vector3d GetCameraPosition() { return Eigen::Vector3d(0, 0, 0); }
	virtual Eigen::Vector3d GetCameraForward() { return Eigen::Vector3d(0, 0, -1); }
	virtual Eigen::Vector3d GetCameraUp() { return Eigen::Vector3d(0, 1, 0); }

	//IGL_INLINE void init_plugins();
    //IGL_INLINE void shutdown_plugins();
    Viewer();
    virtual ~Viewer();
    // Mesh IO
    IGL_INLINE bool load_mesh_from_file(const std::string & mesh_file_name);
    IGL_INLINE bool save_mesh_to_file(const std::string & mesh_file_name);
   
    // Scene IO
    IGL_INLINE bool load_scene();
    IGL_INLINE bool load_scene(std::string fname);
    IGL_INLINE bool save_scene();
    IGL_INLINE bool save_scene(std::string fname);
    // Draw everything
   // IGL_INLINE void draw();
    // OpenGL context resize
   
    // Helper functions

    IGL_INLINE void open_dialog_load_mesh();
    IGL_INLINE void open_dialog_save_mesh();

	IGL_INLINE void draw() {}
    //void yosi();
    void reset();
    Vector3d startCord=Vector3d(0, 0, 0);
    VectorXd Viewer::findOptVValue(MatrixXd Q_Value, int vOneIndex, int vTwoIndex);
    void removeEdge();
    bool checkCollision();
    bool checkConds(AlignedBox<double, 3> clickBox, AlignedBox<double, 3> toCheckCollisionBox, int i);
    void drawBox(AlignedBox<double, 3> boxToDraw,int i);
    void calcTips();
    void updateDistention();
    void drawAxis();
    double returnAngle(Vector3d RD, Vector3d RE);
    void fabrikStart();
    bool canMove(int index, double angleToMove);
    void Viewer::fixZAxis();
    ////////////////////////
    // Multi-mesh methods //
    ////////////////////////

    // Return the current mesh, or the mesh corresponding to a given unique identifier
    //
    // Inputs:
    //   mesh_id  unique identifier associated to the desired mesh (current mesh if -1)
    IGL_INLINE ViewerData& data(int mesh_id = -1);
    IGL_INLINE const ViewerData& data(int mesh_id = -1) const;

    // Append a new "slot" for a mesh (i.e., create empty entries at the end of
    // the data_list and opengl_state_list.
    //
    // Inputs:
    //   visible  If true, the new mesh is set to be visible on all existing viewports
    // Returns the id of the last appended mesh
    //
    // Side Effects:
    //   selected_data_index is set this newly created, last entry (i.e.,
    //   #meshes-1)
    IGL_INLINE int append_mesh(bool visible = true);

    // Erase a mesh (i.e., its corresponding data and state entires in data_list
    // and opengl_state_list)
    //
    // Inputs:
    //   index  index of mesh to erase
    // Returns whether erasure was successful <=> cannot erase last mesh
    //
    // Side Effects:
    //   If selected_data_index is greater than or equal to index then it is
    //   decremented
    // Example:
    //   // Erase all mesh slots except first and clear remaining mesh
    //   viewer.selected_data_index = viewer.data_list.size()-1;
    //   while(viewer.erase_mesh(viewer.selected_data_index)){};
    //   viewer.data().clear();
    //
    IGL_INLINE bool erase_mesh(const size_t index);

    // Retrieve mesh index from its unique identifier
    // Returns 0 if not found
    IGL_INLINE size_t mesh_index(const int id) const;

	Eigen::Matrix4d CalcParentsTrans(int indx);
	inline bool SetAnimation() { return isActive = !isActive; }
public:
    //////////////////////
    // Member variables //
    //////////////////////

    // Alec: I call this data_list instead of just data to avoid confusion with
    // old "data" variable.
    // Stores all the data that should be visualized
    std::vector<ViewerData> data_list;
	
	std::vector<int> parents;
    std::vector<int> parentsTemp = parents;
    size_t selected_data_index;
    int next_data_id;
	bool isPicked;
	bool isActive;

    

    // List of registered plugins
//    std::vector<ViewerPlugin*> plugins;

    // Keep track of the global position of the scrollwheel
    float scroll_position;

  public:
    EIGEN_MAKE_ALIGNED_OPERATOR_NEW
  };

} // end namespace
} // end namespace
} // end namespace

#ifndef IGL_STATIC_LIBRARY
#  include "Viewer.cpp"
#endif

#endif
